### PR TITLE
updated button/download css

### PR DESCRIPTION
**Pull request by muthu-pal**

### CODE REVIEW

**Review by icevin — CHANGES_REQUESTED** [review]
Looks great so far! A couple things to look into:
- The asset boxes look great for logos, but the padding is off for wordmarks, since they're wide and rectangular. Can you figure out a way to fix this?
- When the asset is light or white, it gets lost on the white background. Can you add an option to specify background color via the Liquid templating? 
- The title text isn't being styled or centered properly - from what I can tell, the `padding` is only giving it ~8 pixels of height to work with, which is causing issues.
- Can you try adding in the download icon, and linking it to the download?

Let me know if you have any questions!

**Comment by tfukaza** [comment]
Also a more dev-related tip, make sure to provide a brief explanation of what you updated in your PR, so other members know what to review.

**Comment by muthu-pal** [comment]
- added download icon on asset boxes
- centered title on asset boxes
- changed background of light assets to black
- fixed padding on wordmarks

**Comment by tfukaza** [comment]
@muthu-pal , can you try to resolve the conflict?

**Review by icevin — APPROVED** [review]
Looks good to me! At some point, we should definitely add css/master.css to .gitignore to reduce merge conflicts.

**Pull request merged**
